// src/components/forms/InputHightlight.svelte
<script lang="ts">
	export let icon = ''
	export let name: string = ''
	export let type: string = 'text'
	export let placeholder = ''
	export let value = null
</script>

<div class="flex items-center justify-center">
	<label for={name}>
		<img src={icon} />
	</label>
	<input
		id={name}
		{name}
		{type}
		class="border-none outline-none bg-transparent text-lg text-white pl-2 tracking-wider w-full"
		autocomplete="off"
		{placeholder}
		{value}
	/>
</div>

// src/shared/components/forms/InputHightlight.tsx
import Image from 'next/image';
import { type ReactNode, type InputHTMLAttributes } from 'react';
import { motion } from 'framer-motion';

interface InputHightlightProps {
  icon: string;
  name: string;
  inputProps: InputHTMLAttributes<HTMLInputElement>;
  children?: ReactNode;
}
export default function InputHightlight({
  icon,
  name,
  inputProps,
  children,
}: InputHightlightProps) {
  return (
    <div className="flex items-center justify-start gap-2 mx-auto w-full">
      <motion.label
        initial={{
          x: -10,
          opacity: 0,
        }}
        animate={{
          x: 0,
          opacity: 1,
        }}
        htmlFor={name}
      >
        <Image src={icon} role="img" alt={name} width={30} height={30} />
      </motion.label>
      <motion.div
        initial={{
          x: 10,
          opacity: 0,
        }}
        animate={{
          x: 0,
          opacity: 1,
        }}
      >
        <input
          id={name}
          name={name}
          aria-labelledby="input-label"
          aria-expanded="false"
          aria-controls="input-options"
          {...inputProps}
          role="combobox"
          aria-autocomplete="none"
          autoComplete="off"
          className="border-none outline-none bg-black text-white pl-2 w-full autofill:bg-black autofill:focus-within:bg-black max-w-[220px]"
        />
      </motion.div>
      {children}
    </div>
  );
}
